### ISSUE TITLE
missing status bar on the web version when the synthesis request is being processed

### ISSUE THREAD

**Issue by rlisahuang** [UCSD-PL/vscode#13]

**Comment by KasraF** [comment]
Implemented a draft in

- [Leap server](https://github.com/KasraF/leap-server/commit/26eaf1d87690c58d6d8fca94505fe6acc233fbae)
- [VSCode](https://github.com/UCSD-PL/vscode/commit/9c846f047b034f447fb8c9be09f2f41b19920a5e)

The spec for SSE (which the OpenAI API uses for streaming the results back) doesn't officially support POST requests or request bodies, so re-implementing a 1-1 API on `leap-server` is... messy at best.

So, for now, these commits just use a lower-level interface to keep track of the download progress from the server using a traditional HTTP request and response. If need be, we _can_ reimplement this using the SSE protocol, or simply have some post-processing code in `LeapUtils.ts` to imitate SSE responses. But this should work well enough for now.
