### ISSUE TITLE
code suggestions has wrong indentations in the exploration panel

### ISSUE THREAD

**Issue by rlisahuang** [UCSD-PL/vscode#37]
<img width="1408" alt="Screenshot 2023-03-03 at 9 19 46 AM" src="https://user-images.githubusercontent.com/29112035/222785866-64f546a4-2ffb-4791-b25e-747b158b2aa0.png">

I expected the lines below the `for` header to be outdented by 1 level.

**Comment by KasraF** [comment]
Addressed in d82aba8 by adding spaces (based on cursor position) at the start of the completion when rendering it. This should allow for cases where future lines have _smaller_ indentation than the first line as well.

@rlisahuang Can you please test and close if fixed?
