### ISSUE TITLE
`plt.clf()` is inserted (and saved) in users' code on the web version

### ISSUE THREAD

**Issue by KasraF** [UCSD-PL/vscode#38]
Our code inserts a `plt.clf()` which happens _before_ we save the code, so if the user refreshes their page, they see spurious `plt.clf()` calls in the code which they didn't write:
![image](https://user-images.githubusercontent.com/11238981/222786431-6926979e-5c31-4dea-8d12-52b10b59c439.png)

**Comment by rlisahuang** [comment]
@KasraF Close if it is no longer an issue / unable to be replicated?

**Comment by KasraF** [comment]
> @KasraF Close if it is no longer an issue / unable to be replicated?

It _is_ an issue! Simply copy this code in the editor on the web:
```py
plt.show()
```
and refresh the page. You will see
```py
plt.clf()
```
instead :(

**Comment by KasraF** [comment]
Fixed in ad509869d1ac7fb06f53d1fb1941dfab349732d6.
