### ISSUE TITLE
PBs stop after 100 statements

### ISSUE THREAD

**Issue by michaelbjames** [UCSD-PL/vscode#40]
In Advent of Code, a participant may easily write more than 100 statements. The PBs stop without explanation.

Either:
1. Increase the limit to 300 statements
2. Surface a PB when the limit is hit to say that the code is too long.

**Comment by KasraF** [comment]
I added custom handling for showing an Exception-style message in the Projection Box when the maximum is reached in 9a5125a3a5ca968f6b16c48afbe8e3e3e1ddcd55.

However, it looks like the current actual execution limit is 1000 "line" executions, not 100.

@michaelbjames Do you still have the code that lead to reaching this limit in your pilot? I wonder if we're counting execution inside library functions as well and this is a bug.

Otherwise, I suggest doubling the execution limit for now?

**Comment by rlisahuang** [comment]
The exception reporting is very helpful. Thanks @KasraF !! My pilot study today encountered the limit maximum issue again in the AoC task. I recorded the timestamp of when the issue occurred so we could check the recording for the code that triggered the issue.

**Comment by rlisahuang** [comment]
Code:

```py
starting_template = "NNCB"
template_rules = """
CH -> B
HH -> N
CB -> H
NH -> C
HB -> C
HC -> B
HN -> C
NN -> C
BH -> H
NC -> B
NB -> B
BN -> B
BB -> N
BC -> B
CC -> N
CN -> C
"""


def parse(template_rules):
    rules = template_rules.strip().split("\n")
    rule_set = dict()
    for r in rules: 
        tokens = r.split(" -> ")
        start = tokens[0].strip()
        end = tokens [-1]
        rule_set[start] = end
    return rule_set

def insert (template, rule_set):
    return_template = ""
    for i in range(0, len(template) -1):
        key = template[i:i+2]
        # Given key, find value in rule set and insert value Zetween the two characters of key
        if key in rule_set:
            return_template += key [0] + rule_set[key] + key[1]
        else:
            return_template += key
    return return_template

rule_set = parse(template_rules)
for i in range (5):
    result = insert(starting_template, rule_set)
    starting_template = result

result
```

Exception thrown at line 37.

**Comment by rlisahuang** [comment]
@KasraF Can you look into this again with the code I provided above?

**Comment by slerner** [comment]
For the code that @rlisahuang provided, after a quick assessment, we are not counting executed lines in libraries. I this code is running more than 1000 steps, as far as I can tell. If you change the limit to 2000 you don't hit the exception. Or if you change "for i in range(5)" to "for i in range(2)", you also don't hit the exception.

**Comment by KasraF** [comment]
Increased the limit to 2048 in 4096a047347c9c2fbae419a3062e0d7a7fa5d84c. This should avoid the exception in our study tasks. Closing the issue.
