### ISSUE TITLE
selection highlight missing if the selection is within an inserted code suggestion block

### ISSUE THREAD

**Issue by rlisahuang** [UCSD-PL/vscode#47]
Could be some CSS conflict. Worst case we would use opacity instead of color change to decorate the insertion.

**Comment by slerner** [comment]
Just for additional info, this does not happen if you use any of the classnames suggested in the comment, eg: className: 'selectionHighlight' gives the thing below

![image](https://user-images.githubusercontent.com/2334698/224492551-ef1f184e-e703-4cc7-a247-2c2874e260f3.png)

**Comment by rlisahuang** [comment]
@slerner Yes I noticed that. I doubt it is due to some CSS conflict but will need to investigate more with CSS inspection. I'll get to it later today / tomorrow unless you are fixing it now.

**Comment by rlisahuang** [comment]
the suggested classnames don't allow you to configure customized colors though unless you override some source code.

Plan B for this one is switch to opacity-based highlighting if the existing conflict couldn't be resolved.

**Comment by rlisahuang** [comment]
Fixed in 6232d6d898a5a852db625de3a532bdf73f8a840b.
